### ISSUE TITLE
Bot returns a bad value for prefer-encrypt

### ISSUE THREAD

**Issue by r10s** [hpk42/muacrypt#12]
The bot returns the Autocrypt-header with the `prefer-encrypt=notset` which is out of spec.

Only `prefer-encrypt=mutal` is allowed; for "no preference", prefer-encrypt must not be specified at all, see https://autocrypt.readthedocs.io/en/latest/level1.html#the-autocrypt-header

**Comment by azul** [comment]
Just checked and currently the bot does not send any prefer encrypt.
bot-mutual has not replied yet... now it did. Sending prefer-encrypt=mutual
