### ISSUE TITLE
Can I force incoming mails to be encrypted for my key?

### ISSUE THREAD

**Issue by ConorIA** [hpk42/muacrypt#13]
I run my own mailserver (based on https://github.com/tomav/docker-mailserver). I have leveraged a Perl script called [gpgit](https://gitlab.com/mikecardwell/gpgit) so that my emails are automatically encrypted when they arrive on my server. This was mostly a curiosity project, and I know that this isn't e2e, given that they leave the sender's server in plaintext. 

I am considering replacing gpgit with autocrypt. I have read through the documentation, but I can't seem to find an option to force autocrypt to encrypt incoming emails for a given key. Is this possible in the current python solution? 

EDIT: I forgot to link to my current solution: https://github.com/ConorIA/dockerfiles/tree/master/gpgit

**Comment by hpk42** [comment]
No, it's not possible yet but i'd like to add support for encrypting and decrypting mime message eventually.

**Comment by hpk42** [comment]
while muacrypt-0.9.0 supports encryption and decryption of outgoing/incoming messages the mode of encrypting incoming ones currently does not make sense, see eg the "mutt" documentation page of the latest release.  For now, i don't see a direct use case so closing this issue.
