### ISSUE TITLE
Implement recommendations algorithm

### ISSUE THREAD

**Issue by hpk42** [hpk42/muacrypt#26]
The https://autocrypt.org/level1.html#provide-a-recommendation-for-message-encryption needs to be fully implemented, depends on or relates to #25. 

the idea is to also expose the recommendation algorithm via a new ``recommend`` sub command so that MUAs can use it to query the recommendation for one or more recipients.

**Comment by azul** [comment]
Looks like what we want is a command line 
```sh
muacrypt recommendation e-mailaddress [another-emailaddress, ...]
```
Based on account API account.get_recommendation(emailadrlist)

**Comment by azul** [comment]
#48 made some progress towards this. Still missing:
- [ ] bot integration
- [ ] checking if keys expired
- [ ] check if keys have been revoked
- [ ] gossip (not implemented in other places yet)
- [ ] command line interface

**Comment by hpk42** [comment]
i don't think we should check if keys are expired or revoked with this issue because L1 does not mandate this strictly. We can create an "check if key is invalid" issue instead, for future refinements.
