### ISSUE TITLE
Create mutt/imap-sync page

### ISSUE THREAD

**Issue by hpk42** [hpk42/muacrypt#31]
Experiment and document how muacrypt can be integrated with mutt, either with this repository or on the https://github.com/autocrypt/autocrypt pages. This might also include guidance on how to setup and integrate muacrypt with offlineimap or isync-like tools which synchronize imap state with a local directory.

**Comment by hpk42** [comment]
from a discussion with @valodim and gfa a few suggestions on what to look at wrt mutt config (muttrc integration): 

- unignore the Autocrypt header and set ``display_filter = muacrypt ...`` which can then parse incoming direct Autocrypt headers at display time (this misses Gossip headers though) 

- set [message_hook](https://superuser.com/questions/1224053/configuring-mutt-to-pipe-a-mail-to-a-command-when-viewing-for-the-first-time) to route new incoming message to muacrypt process-incoming 

- for adding headers one can set ``sendmail`` to use ``muacrypt sendmail`` already (i used this in practise, it works).   

- to get gossip headers one could try to write a wrapper via ``pgp_decrypt_command`` which sees and decrypts each message -- if people use passphrases, it will also ask for it at the right time. 

- on syncing mail from remote (offlineimap, mbsync, ...) muacrypt could offer a way to scan new messages from non-spam INBOXes, recording what it saw already and parsing what is new.  This is problematic if decryption requires a passphrase (it depends on which keys people use)

**Comment by gfa** [comment]
Setting  in muttrc

```
unignore Autocrypt 
set display_filter="muacrypt process-incoming"
```

muacrypt will importing keys, mutual settings, etc. after opening them
 
Unfortunately its eating the output so I can't really read the emails :P

I'll test with bot-mutual after I repair my setup (playing with python versions ATM)

**Comment by hpk42** [comment]
ok, process-incoming needs to grow an option to output the processed mail.

what exactly does display_filter provide? the decrypted mail with
all headers, also Autocrypt-Gossip? (you can just have a shell-script 
which saves and also outputs the mail)

**Comment by gfa** [comment]
I'm using a very simple script to save the email, feed it to muacrypt and display it
```
#!/bin/sh
TEMP=$(mktemp)
cat > $TEMP
muacrypt process-incoming 2>>/tmp/muacrypt.log >>/tmp/muacrypt.log <$TEMP
cat $TEMP                                                                                                                                                                                                                                                     
rm -f $TEMP
```

mutt feeds the _decrypted_ email to display_filter, which makes me thing it could be used to retrieve gossip headers

**Comment by shtrom** [comment]
> ok, process-incoming needs to grow an option to output the processed mail.

Heh, I've just starting growing such an option here https://github.com/shtrom/muacrypt/tree/process-pipe

Not completely done yet, as I'm testing out my mutt config at the same time.

One note, though, perhaps all user-interactive message should be output to STDERR by default, rather than STDIN. This would help building shell pipelines.

**Comment by hpk42** [comment]
On Tue, May 15, 2018 at 04:39 -0700, Olivier Mehani wrote:
> > ok, process-incoming needs to grow an option to output the processed mail.
> 
> Heh, I've just starting growing such an option here https://github.com/shtrom/muacrypt/tree/process-pipe
> 
> Not completely done yet, as I'm testing out my mutt config at the same time.
> 
> One note, though, perhaps all user-interactive message should be output to STDERR by default, rather than STDIN. This would help building shell pipelines.

yes, i agree i think.

**Comment by hpk42** [comment]
i don't think that "display_filter" can be used as it doesn't provide Autocrypt or Autocrypt-gossip headers.  

The original issue was about a mutt page which exists now: 

https://muacrypt.readthedocs.io/mutt.html

please open more specific issues if you want. thanks!

**Comment by shtrom** [comment]
After a lot of delay, I can confirm that `display_filter` is not gonna work very well, as Mutt only passes the headers that will actually get displayed to the user. We could `unignore` the `Autocrypt` headers, but yeah, it's not nice. Particularly now that `muacrypt` has a `scandir-incoming`.
